title: "Mis historias"
author: "Mustafa Ali Saba"
description: "Relatos de ficción breve y mundos imaginarios"

email: mustafa.ali.saba@protonmail.com
instagram: https://www.instagram.com/mustafa.ali.sab/

theme: minima

collections:
  stories:
    output: true
    permalink: /historias/:title/

copyright: "© 2026 Mustafa Ali Saba. Todos los derechos reservados."

