title: "Mis historias"
author: "Mustafa Ali Saba"
description: "Relatos de ficción breve y mundos imaginarios"

email: roberto@email.com
instagram: https://instagram.com/tuusuario

theme: minima

collections:
  stories:
    output: true
    permalink: /historias/:title/

copyright: "© 2026 Mustafa Ali Saba. Todos los derechos reservados."

